module.exports = {

	// display:
	"image/jpeg":    { type: "image", ext: "jpg" },
	"image/jpg":     { type: "image", ext: "jpg" },
	"image/png":     { type: "image", ext: "png" },
	"image/gif":     { type: "image", ext: "gif" },
	"image/svg":     { type: "image", ext: "svg" },
	"image/svg+xml": { type: "image", ext: "svg+xml" },
	"image/webp":    { type: "image", ext: "webp" },
	"audio/aac":     { type: "audio", ext: "aac" },
	"audio/flac":    { type: "audio", ext: "flac" },
	"audio/mpeg":    { type: "audio", ext: "mp3" },
	"audio/mp3":     { type: "audio", ext: "mp3" },
	"audio/mp4":     { type: "audio", ext: "m4a" },
	"audio/x-m4a":   { type: "audio", ext: "m4a" },
	"audio/ogg":     { type: "audio", ext: "ogg" },
	"audio/wav":     { type: "audio", ext: "wav" },
	"audio/webm":    { type: "audio", ext: "webm" },
	"video/ogg":     { type: "video", ext: "ogv" },
	"video/mpeg":    { type: "video", ext: "mpeg" },
	"video/mp4":     { type: "video", ext: "mp4" },
	"video/webm":    { type: "video", ext: "webm" },	

	// download only
	"image/tiff":         { type: "image", ext: "tif" },
	"image/vnd.wap.wbmp": { type: "image", ext: "wbmp" },
	"image/x-icon":       { type: "image", ext: "ico" },
	"image/x-jng":        { type: "image", ext: "jng" },
	"image/x-ms-bmp":     { type: "image", ext: "bmp" },
	"audio/midi":    { type: "file", ext: "mid" },
	"audio/x-realaudio": { type: "file", ext: "ra" },
	"video/3gpp":      { type: "video", ext: "3gpp" },
	"video/mp2t":      { type: "video", ext: "ts" },
	"video/quicktime": { type: "video", ext: "mov" },
	"video/x-flv":     { type: "video", ext: "flv" },
	"video/x-m4v":     { type: "video", ext: "m4v" },
	"video/x-mng":     { type: "video", ext: "mng" },
	"video/x-ms-asf":  { type: "video", ext: "asx" },
	"video/x-ms-wmv":  { type: "video", ext: "wmv" },
	"video/x-msvideo": { type: "video", ext: "avi" },
	"text/csv":   { type: "file", ext: "csv" },
	"text/tsv":   { type: "file", ext: "tsv" },
	"text/html":  { type: "file", ext: "html" },
	"text/css":   { type: "file", ext: "css" },
	"text/xml":   { type: "file", ext: "xml" },
	"text/plain": { type: "file", ext: "txt" },
	"application/xhtml+xml":  { type: "file", ext: "html" },
	"application/javascript": { type: "file", ext: "js" },
	"application/json":       { type: "file", ext: "json" },
	"application/atom+xml":   { type: "file", ext: "atom" },
	"application/rss+xml":    { type: "file", ext: "rss" },
	"application/postscript": { type: "file", ext: "ps" },
	"application/pdf":        { type: "file", ext: "pdf" },
	"application/vnd.google-earth.kml+xml": { type: "file", ext: "kml" },
	"application/vnd.google-earth.kmz":     { type: "file", ext: "kmz" },
	"application/x-7z-compressed":  { type: "file", ext: "7z" },
	"application/x-rar-compressed": { type: "file", ext: "rar" },
	"application/zip":              { type: "file", ext: "zip" },
	"application/vnd.ms-excel": { type: "file", ext: "xls" },
	"application/vnd.ms-fontobject": { type: "file", ext: "eot" },
	"application/vnd.ms-powerpoint": { type: "file", ext: "ppt" },
	"application/rtf": { type: "file", ext: "rtf" },
	"application/msword": { type: "file", ext: "doc" },
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document":   { type: "file", ext: "docx" },
	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":         { type: "file", ext: "xlsx" },
	"application/vnd.openxmlformats-officedocument.presentationml.presentation": { type: "file", ext: "pptx" },

	// in case someone is stupid
	".php": { type: "file", ext: "phps" },

};
